import type { Metadata } from "next";
import { inter } from "@/config/fonts";

import "./globals.css";
import { TopMenu } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <TopMenu />
        {children}
      </body>
    </html>
  );
}
